Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -3,7 +3,7 @@ name: CI/CD Pipeline
 on:
   push:
     branches:
-      - main
+      - main  # ou la branche que vous utilisez pour le déploiement
 
 jobs:
   build-and-test:
@@ -16,7 +16,7 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
-        python-version: '3.9' 
+        python-version: '3.9'  # utilisez la version Python nécessaire pour votre projet
 
     - name: Create and activate virtual environment
       run: |
@@ -29,14 +29,14 @@ jobs:
         pip install --upgrade pip
         pip install -r requirements.txt
 
-    # - name: Run tests
-    #   run: |
-    #     source venv/bin/activate
-    #     pytest
+    - name: Run tests
+      run: |
+        source venv/bin/activate
+        pytest
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build-and-test
+    needs: build-and-test  # Attendez que le job de build-and-test soit terminé
 
     steps:
     - name: Checkout repository
@@ -44,6 +44,9 @@ jobs:
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
+
+    - name: Log in to Docker Hub
+      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
     - name: Cache Docker layers
       uses: actions/cache@v3
@@ -53,20 +56,9 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-buildx-
 
-    # - name: Log in to Docker Hub
-    #   uses: docker/login-action@v2
-    #   with:
-    #     username: ${{ secrets.DOCKER_USERNAME }}
-    #     password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Log in to Docker Hub
-      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-      # docker login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} | ${{ secrets.DOCKER_PASSWORD }} --password-stdin
-      # echo ${{ secrets.DOCKER_PASSWORD }} | echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
-      
-        
     - name: Build and push Docker image
       run: |
+        cd fastapi  # Assurez-vous de changer le répertoire vers le bon contexte
         docker-compose build
         docker-compose push
 
@@ -79,7 +71,13 @@ jobs:
         echo "$SSH_PRIVATE_KEY" > id_rsa
         chmod 600 id_rsa
         ssh -i id_rsa -o StrictHostKeyChecking=no $USER@$HOST << EOF
-          cd /home/ec2-user/myfastapiapp/fastapi-TP
-          docker-compose pull
-          docker-compose up -d
+          cd /home/***/myfastapiapp/fastapi-TP
+          ls -l  # Vérifie le contenu du répertoire
+          if [ -f docker-compose.yml ]; then
+            docker-compose pull
+            docker-compose up -d
+          else
+            echo "docker-compose.yml not found in /home/***/myfastapiapp/fastapi-TP"
+            exit 1
+          fi
         EOF
